apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: gcp-gpu-monitor
  annotations:
    use: "gcp-gpu-monitor"
spec:
  selector:
    matchLabels:
      name: gcp-gpu-monitor
  template:
    metadata:
      labels:
        name: gcp-gpu-monitor
    spec:
#      nodeSelector:
#        node_pool: gpu_nodes
      containers:
      - name: gcp-gpu-monitor
        image: bhgedigital/gcp-gpu-monitor:v1-cuda10
        imagePullPolicy: Always
        env:
#        - name: GOOGLE_CLOUD_PROJECT
#          value: ""
        - name: GPU_REPORTING_FREQUENCY
          value: 60
